// Lista completa dos livros da Bíblia com nomes em português e inglês (para a API)
export const books = [
  // Antigo Testamento
  { portuguese: "Gênesis", english: "genesis", chapters: 50 },
  { portuguese: "Êxodo", english: "exodus", chapters: 40 },
  { portuguese: "Levítico", english: "leviticus", chapters: 27 },
  { portuguese: "Números", english: "numbers", chapters: 36 },
  { portuguese: "Deuteronômio", english: "deuteronomy", chapters: 34 },
  { portuguese: "Josué", english: "joshua", chapters: 24 },
  { portuguese: "Juízes", english: "judges", chapters: 21 },
  { portuguese: "Rute", english: "ruth", chapters: 4 },
  { portuguese: "1 Samuel", english: "1_samuel", chapters: 31 },
  { portuguese: "2 Samuel", english: "2_samuel", chapters: 24 },
  { portuguese: "1 Reis", english: "1_kings", chapters: 22 },
  { portuguese: "2 Reis", english: "2_kings", chapters: 25 },
  { portuguese: "1 Crônicas", english: "1_chronicles", chapters: 29 },
  { portuguese: "2 Crônicas", english: "2_chronicles", chapters: 36 },
  { portuguese: "Esdras", english: "ezra", chapters: 10 },
  { portuguese: "Neemias", english: "nehemiah", chapters: 13 },
  { portuguese: "Ester", english: "esther", chapters: 10 },
  { portuguese: "Jó", english: "job", chapters: 42 },
  { portuguese: "Salmos", english: "psalms", chapters: 150 },
  { portuguese: "Provérbios", english: "proverbs", chapters: 31 },
  { portuguese: "Eclesiastes", english: "ecclesiastes", chapters: 12 },
  { portuguese: "Cantares", english: "song_of_solomon", chapters: 8 },
  { portuguese: "Isaías", english: "isaiah", chapters: 66 },
  { portuguese: "Jeremias", english: "jeremiah", chapters: 52 },
  { portuguese: "Lamentações", english: "lamentations", chapters: 5 },
  { portuguese: "Ezequiel", english: "ezekiel", chapters: 48 },
  { portuguese: "Daniel", english: "daniel", chapters: 12 },
  { portuguese: "Oséias", english: "hosea", chapters: 14 },
  { portuguese: "Joel", english: "joel", chapters: 3 },
  { portuguese: "Amós", english: "amos", chapters: 9 },
  { portuguese: "Obadias", english: "obadiah", chapters: 1 },
  { portuguese: "Jonas", english: "jonah", chapters: 4 },
  { portuguese: "Miquéias", english: "micah", chapters: 7 },
  { portuguese: "Naum", english: "nahum", chapters: 3 },
  { portuguese: "Habacuque", english: "habakkuk", chapters: 3 },
  { portuguese: "Sofonias", english: "zephaniah", chapters: 3 },
  { portuguese: "Ageu", english: "haggai", chapters: 2 },
  { portuguese: "Zacarias", english: "zechariah", chapters: 14 },
  { portuguese: "Malaquias", english: "malachi", chapters: 4 },
  // Novo Testamento
  { portuguese: "Mateus", english: "matthew", chapters: 28 },
  { portuguese: "Marcos", english: "mark", chapters: 16 },
  { portuguese: "Lucas", english: "luke", chapters: 24 },
  { portuguese: "João", english: "john", chapters: 21 },
  { portuguese: "Atos", english: "acts", chapters: 28 },
  { portuguese: "Romanos", english: "romans", chapters: 16 },
  { portuguese: "1 Coríntios", english: "1_corinthians", chapters: 16 },
  { portuguese: "2 Coríntios", english: "2_corinthians", chapters: 13 },
  { portuguese: "Gálatas", english: "galatians", chapters: 6 },
  { portuguese: "Efésios", english: "ephesians", chapters: 6 },
  { portuguese: "Filipenses", english: "philippians", chapters: 4 },
  { portuguese: "Colossenses", english: "colossians", chapters: 4 },
  { portuguese: "1 Tessalonicenses", english: "1_thessalonians", chapters: 5 },
  { portuguese: "2 Tessalonicenses", english: "2_thessalonians", chapters: 3 },
  { portuguese: "1 Timóteo", english: "1_timothy", chapters: 6 },
  { portuguese: "2 Timóteo", english: "2_timothy", chapters: 4 },
  { portuguese: "Tito", english: "titus", chapters: 3 },
  { portuguese: "Filemom", english: "philemon", chapters: 1 },
  { portuguese: "Hebreus", english: "hebrews", chapters: 13 },
  { portuguese: "Tiago", english: "james", chapters: 5 },
  { portuguese: "1 Pedro", english: "1_peter", chapters: 5 },
  { portuguese: "2 Pedro", english: "2_peter", chapters: 3 },
  { portuguese: "1 João", english: "1_john", chapters: 5 },
  { portuguese: "2 João", english: "2_john", chapters: 1 },
  { portuguese: "3 João", english: "3_john", chapters: 1 },
  { portuguese: "Judas", english: "jude", chapters: 1 },
  { portuguese: "Apocalipse", english: "revelation", chapters: 22 }
];